version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-giraffe-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1flalgsb9l2a5"
s3_prefix = "serverless-giraffe-demo"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
